[terminal]
shell = { program = "/opt/homebrew/bin/zellij", args = ["options", "--default-shell", "/opt/homebrew/bin/nu"] }
[window]
startup_mode = "Maximized"
padding = { x = 8, y = 8 }
decorations = "Buttonless"
opacity = 0.7
blur = true
option_as_alt = "Both"
[font]
size = 17
